# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MarvelCharacters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Marvel
  pod "Anchorage"
  pod 'SwiftLint'
  pod 'CryptoSwift'
  pod 'Moya'
  pod 'Moya/Combine'
  pod 'Kingfisher'
  
  target 'MarvelCharactersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelCharactersUITests' do
    # Pods for testing
  end

end
